FROM node:22-alpine

WORKDIR /app

# Copy dependency definition files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application source code
COPY . .

EXPOSE 5173

# Default CMD (executed when running the image directly via docker run)
CMD ["npm", "run", "dev", "--", "--host"]