FROM node:22-slim

# Install dependencies required for stable execution of headless Puppeteer on Linux + emoji fonts
RUN apt-get update && apt-get install -y \
    chromium \
    fonts-ipafont-gothic \
    fonts-wqy-zenhei \
    fonts-thai-tlwg \
    fonts-kacst \
    fonts-freefont-ttf \
    fonts-noto-color-emoji \
    libxss1 \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

# Set the global environment variables for Chromium inside the container
ENV PUPPETEER_SKIP_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium

# Install local dependencies, generate Prisma client, and install nodemon globally
RUN npm install && npx prisma generate && npm install -g nodemon

COPY . .

EXPOSE 3001

# Start the server with live file watching
CMD ["nodemon", "server.js"]